image: python:3.8

test:
  stage: test
  script:
  - pip install -U 'sphinx==3.5.4'
  - pip install -U numpy
  - pip install -U 'sphinx-rtd-theme==0.5.2'
  - pip install -U sphinx-multiversion
  - pip install -U pybind11 
  - make
  - . ./set_env.sh
  - make check
  - sphinx-build -b html doc/ public
  only:
  - branches
  except:
  - main

pages:
  stage: deploy
  script:
  - pip install -U 'sphinx==3.5.4'
  - pip install -U numpy
  - pip install -U 'sphinx-rtd-theme==0.5.2'
  - pip install -U sphinx-multiversion
  - pip install -U pybind11 
  - make
  - . ./set_env.sh
  - sphinx-multiversion doc/ public
  artifacts:
    paths:
    - public/main
  only:
  - main
